apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cypress-parallel
  annotations:
    github.com/project-slug: stevenmchaves/cypress-parallel
spec:
  type: other
  lifecycle: experimental
  owner: stevenmchaves
